name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: 安装依赖
      run: |
        npm install

    - name: 运行测试
      run: |
        npm run test

    - name: 构建应用
      run: |
        npm run build

    - name: 打包应用
      run: |
        npm run package 